modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="rakinator"
version="1.0.0"
displayName="Rakinator"
credits="Drakma"
displayURL="http://drakma.tv"
authors="Drakma"

[[dependencies.rakinator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

