modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="rakinator"
version="1.0.0"
displayName="Rakinator"
credits="Drakma"
displayURL="https://mcreator.net"
authors="Drakma"

[[dependencies.rakinator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.rakinator]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

